In [1]:
import cv2
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
import pandas as pd
import os
import shutil

In [2]:
def average_BGR(image):
    avg_blue = image[:,:,0].mean()
    avg_green = image[:,:,1].mean()
    avg_red = image[:,:,2].mean()

    return [avg_blue,avg_green,avg_red]

def average_HSV(image):
    image = cv2.cvtColor(image,cv2.COLOR_BGR2HSV)
    avg_hue = image[:,:,0].mean()
    avg_saturation = image[:,:,1].mean()
    avg_value = image[:,:,2].mean()

    return avg_hue, avg_saturation, avg_value

In [6]:
list_avg_blue = []
list_avg_green = []
list_avg_red = []

list_avg_hue=[]
list_avg_saturation=[]
list_avg_value=[]
X1 = []
X2 = []
list_image = []
list_image_path=[]
for dirname, _, filenames in os.walk('D:\\Nhat\\term_8\\MDS\\src\\Mix'):
    for filename in filenames:
        image_path = os.path.join(dirname, filename)
        list_image_path.append(image_path)
        image = cv2.imread(image_path)
        list_image.append(image)
        avg_BGR = average_BGR(image)
        X1.append(avg_BGR)
        list_avg_blue.append(avg_BGR[0])
        list_avg_green.append(avg_BGR[1])
        list_avg_red.append(avg_BGR[2])
        avg_HSV= average_HSV(image)
        list_avg_hue.append(avg_HSV[0])
        list_avg_saturation.append(avg_HSV[1])
        list_avg_value.append(avg_HSV[2])
        X2.append(avg_HSV)

In [7]:
from sklearn.cluster import KMeans
kmeans1 = KMeans(n_clusters=10,random_state =0)

X1 = np.array(X1)

kmeans1.fit(X1)


print('Centers found by scikit-learn:')
# print(kmeans1.cluster_centers_)
pred_label = kmeans1.predict(X1)
# print(pred_label)

# for i in range(10):
#     folder_name = str(i)
#     os.mkdir(os.path.join('D:\PTIT\CSDLDPT\Multimedia-Database-System\kmeans1', folder_name))

dict = {}

for i in range(len(list_image_path)):
    dict[list_image_path[i]] = pred_label[i]

for key, value in dict.items():
    for dirname, child_folders, filenames in os.walk('kmeans1'):
        for folder in child_folders:
            if str(value) == folder:
                shutil.copy(key, os.path.join(dirname, folder))

for key, value in dict.items():
    if(value == 1):
        print(key, ':', value)

c:\Users\nhat2\anaconda3\envs\khdl\Lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\Users\nhat2\anaconda3\envs\khdl\Lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


Centers found by scikit-learn:
D:\Nhat\term_8\MDS\src\Mix\Avocado (07).jpg : 1
D:\Nhat\term_8\MDS\src\Mix\Avocado (08).jpg : 1
D:\Nhat\term_8\MDS\src\Mix\Avocado (09).jpg : 1
D:\Nhat\term_8\MDS\src\Mix\Avocado (12).jpg : 1
D:\Nhat\term_8\MDS\src\Mix\Avocado (13).jpg : 1
D:\Nhat\term_8\MDS\src\Mix\Avocado (14).jpg : 1
D:\Nhat\term_8\MDS\src\Mix\Cherry (01).jpg : 1
D:\Nhat\term_8\MDS\src\Mix\Cherry (02).jpg : 1
D:\Nhat\term_8\MDS\src\Mix\Cherry (03).jpg : 1
D:\Nhat\term_8\MDS\src\Mix\Cherry (04).jpg : 1
D:\Nhat\term_8\MDS\src\Mix\Cherry (05).jpg : 1
D:\Nhat\term_8\MDS\src\Mix\Cherry (06).jpg : 1
D:\Nhat\term_8\MDS\src\Mix\Cherry (07).jpg : 1
D:\Nhat\term_8\MDS\src\Mix\Cherry (08).jpg : 1
D:\Nhat\term_8\MDS\src\Mix\Cherry (09).jpg : 1
D:\Nhat\term_8\MDS\src\Mix\Cherry (10).jpg : 1
D:\Nhat\term_8\MDS\src\Mix\Cherry (11).jpg : 1
D:\Nhat\term_8\MDS\src\Mix\Cherry (12).jpg : 1
D:\Nhat\term_8\MDS\src\Mix\Cherry (13).jpg : 1
D:\Nhat\term_8\MDS\src\Mix\Cherry (14).jpg : 1
D:\Nhat\term_8\MDS\src\

In [9]:
kmeans2 = KMeans(n_clusters=11,random_state =0)

X2 = np.array(X2)

kmeans2.fit(X2)

print('Centers found by scikit-learn:')
print(kmeans2.cluster_centers_)

c:\Users\nhat2\anaconda3\envs\khdl\Lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\Users\nhat2\anaconda3\envs\khdl\Lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


Centers found by scikit-learn:
[[ 23.445136    69.189504   143.026044  ]
 [ 21.64722    172.41603333 174.02270667]
 [ 40.60115    127.70924    100.65318   ]
 [ 26.08185789 102.46431579 196.67308947]
 [ 94.03787333  94.54522    107.35758   ]
 [ 18.71273333  52.06017222 223.29955   ]
 [ 73.93074667  15.49567333 165.48607333]
 [ 47.19972258  56.50966452 155.29217419]
 [ 23.34377778  91.30590741 170.39474074]
 [ 23.08768846  69.5241     198.84504615]
 [ 27.94625714  26.74230714 179.83395   ]]


In [10]:
result = []
result_pred_label2 = []
for i in range(11):
  len_label = len([key for key,value1,value2,image in all_list_array if key == i])
  count = len_label//13
  if count >1:
    kmeans2_label1 = KMeans(n_clusters=count ,random_state =0)

    result = [value2 for key,value1,value2,image in all_list_array if key == i]
    result = np.array(result)

    kmeans2_label1.fit(result)

    print('Centers found by scikit-learn:')
    print(kmeans2.cluster_centers_)
    result_pred_label2 = (kmeans2_label1.predict(result))
    # kmeans_display(result, result_pred_label2)
    for index, (key1, key2, image, value1,value2) in enumerate(all_list_image):
      for i in range(len(result_pred_label2)):
          if (value2 == result[i]).all():
              # Tạo một bản sao của tuple hiện tại
              updated_tuple = list(all_list_image[index])
              # Thay đổi giá trị của key2 trong danh sách
              updated_tuple[1] = result_pred_label2[i]
              # Chuyển đổi danh sách đã được cập nhật thành tuple và gán lại vào all_list_image
              all_list_image[index] = tuple(updated_tuple)

NameError: name 'all_list_array' is not defined

In [11]:
tmp = [[] for _ in range(11)]
for key1, key2, image, value1, value2 in all_list_image:
  if key2 != None:
    tmp[key1].append([key2,image,value1,value2])

for index, (i) in enumerate(tmp):
  if len(i)>0:
    print(index)
    for key2,image,value1,value2 in i:
      if key2==0:
        print(image)
    print()
    for key2,image,value1,value2 in i:
      if key2==1:
        print(image)

NameError: name 'all_list_image' is not defined