In [1]:
import cv2 
import matplotlib.pyplot as plt
import numpy as np
import os

In [24]:
def convert_images_to_same(folder_path,qua):
    output_folder = os.path.join(folder_path, "converted")
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)
    
    image_files = [f for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))]
    count = 1 
    for image_file in image_files:
        image_file = os.path.join(folder_path, image_file)
        print(image_file)
        image = cv2.imread(image_file)
        print(image)
        image = cv2.resize(image, (256, 256))
        output_path = os.path.join(output_folder, qua + f'_{count}' + ".jpg")
        cv2.imwrite(output_path, image,[int(cv2.IMWRITE_JPEG_QUALITY), 100])
        count += 1
        
    return output_folder

In [40]:
foler_path = "D:\\Nhat\\term_8\\MDS\\Image_DB\\Fruit\\Phuong\\Otchuong-Phuong"
convert_images_to_same(foler_path,'BellPepper')


D:\Nhat\term_8\MDS\Image_DB\Fruit\Phuong\Otchuong-Phuong\1.jpg
[[[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 ...

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]]
D:\Nhat\term_8\MDS\Image_DB\Fruit\Phuong\Otchuong-Phuong\10.jpg
[[[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 [[253 253 253]
  [253 253 253]
  [

'D:\\Nhat\\term_8\\MDS\\Image_DB\\Fruit\\Phuong\\Otchuong-Phuong\\converted'